export enum ErrorsCodeApp {
  //   The GraphQL operation string contains a syntax error.
  PERSISTED_QUERY_NOT_FOUND = 'PERSISTED_QUERY_NOT_FOUND',
  PERSISTED_QUERY_NOT_SUPPORTED = 'PERSISTED_QUERY_NOT_SUPPORTED',
  OPERATION_RESOLUTION_FAILURE = 'OPERATION_RESOLUTION_FAILURE',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  // AUTH
  UNAUTHENTICATED = 'UNAUTHENTICATED',
  FORBIDDEN = 'FORBIDDEN',
  // VALIDATION_ERROR
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  BAD_USER_INPUT = 'BAD_USER_INPUT',
  GRAPHQL_VALIDATION_FAILED = 'GRAPHQL_VALIDATION_FAILED',
  GRAPHQL_PARSE_FAILED = 'GRAPHQL_PARSE_FAILED',
  BAD_REQUEST = 'BAD_REQUEST',
}
