# docker-compose.yml

version: '3.8'
services:
  # Docker connection string: postgres://postgres:postgres@localhost:5432/

  postgres2:
    image: postgres:13.5
    networks:
      - postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  dbadmin2:
    image: dpage/pgadmin4
    networks:
      - postgres
    restart: always
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin4

networks:
  postgres:
    driver: bridge
    
volumes:
  postgres:
